[2024-09-01T17:48:41.779+0000] {processor.py:161} INFO - Started process (PID=474) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:48:41.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:48:41.783+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:48:41.783+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:48:41.809+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:48:41.807+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:48:41.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:48:41.847+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.078 seconds
[2024-09-01T17:49:12.097+0000] {processor.py:161} INFO - Started process (PID=485) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:49:12.099+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:49:12.103+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:49:12.102+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:49:12.133+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:49:12.130+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:49:12.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:49:12.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.086 seconds
[2024-09-01T17:49:42.587+0000] {processor.py:161} INFO - Started process (PID=496) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:49:42.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:49:42.606+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:49:42.604+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:49:42.940+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:49:42.937+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:49:42.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:49:43.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.439 seconds
[2024-09-01T17:50:13.622+0000] {processor.py:161} INFO - Started process (PID=508) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:50:13.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:50:13.628+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:50:13.627+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:50:13.655+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:50:13.653+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:50:13.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:50:13.688+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.082 seconds
[2024-09-01T17:50:43.956+0000] {processor.py:161} INFO - Started process (PID=519) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:50:43.957+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:50:43.961+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:50:43.960+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:50:43.992+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:50:43.991+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:50:43.993+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:50:44.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.088 seconds
[2024-09-01T17:51:14.785+0000] {processor.py:161} INFO - Started process (PID=531) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:51:14.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:51:14.792+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:51:14.792+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:51:14.814+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:51:14.813+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:51:14.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:51:14.845+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.071 seconds
[2024-09-01T17:51:45.189+0000] {processor.py:161} INFO - Started process (PID=542) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:51:45.191+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:51:45.195+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:51:45.194+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:51:45.245+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:51:45.243+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:51:45.247+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:51:45.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.167 seconds
[2024-09-01T17:52:15.845+0000] {processor.py:161} INFO - Started process (PID=554) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:52:15.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:52:15.865+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:52:15.864+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:52:15.913+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:52:15.911+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:52:15.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:52:16.001+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.171 seconds
[2024-09-01T17:52:46.142+0000] {processor.py:161} INFO - Started process (PID=565) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:52:46.143+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:52:46.146+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:52:46.146+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:52:46.168+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:52:46.165+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:52:46.171+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:52:46.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.084 seconds
[2024-09-01T17:53:17.985+0000] {processor.py:161} INFO - Started process (PID=576) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:53:18.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:53:18.059+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:53:18.058+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:53:19.597+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:53:19.595+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:53:19.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:53:19.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 1.731 seconds
[2024-09-01T17:53:51.914+0000] {processor.py:161} INFO - Started process (PID=587) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:53:51.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:53:52.061+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:53:52.060+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:53:52.148+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:53:52.145+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:53:52.151+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:53:52.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.336 seconds
[2024-09-01T17:54:22.805+0000] {processor.py:161} INFO - Started process (PID=598) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:54:22.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:54:22.811+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:54:22.810+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:54:22.849+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:54:22.847+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:54:22.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:54:22.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.139 seconds
[2024-09-01T17:54:53.111+0000] {processor.py:161} INFO - Started process (PID=609) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:54:53.112+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:54:53.114+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:54:53.114+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:54:53.131+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:54:53.130+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:54:53.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:54:53.165+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.061 seconds
[2024-09-01T17:55:23.345+0000] {processor.py:161} INFO - Started process (PID=620) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:55:23.347+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:55:23.350+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:55:23.349+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:55:23.367+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:55:23.365+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:55:23.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:55:23.412+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.077 seconds
[2024-09-01T17:55:53.615+0000] {processor.py:161} INFO - Started process (PID=631) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:55:53.617+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:55:53.620+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:55:53.619+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:55:53.638+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:55:53.637+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:55:53.639+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:55:53.674+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.071 seconds
[2024-09-01T17:56:23.932+0000] {processor.py:161} INFO - Started process (PID=642) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:56:23.933+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:56:23.937+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:56:23.936+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:56:23.960+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:56:23.957+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:56:23.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:56:24.001+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.076 seconds
[2024-09-01T17:56:54.293+0000] {processor.py:161} INFO - Started process (PID=653) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:56:54.298+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:56:54.309+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:56:54.308+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:56:55.130+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:56:55.127+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:56:55.161+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:56:55.257+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.986 seconds
[2024-09-01T17:57:25.972+0000] {processor.py:161} INFO - Started process (PID=664) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:57:25.973+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:57:25.978+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:57:25.977+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:57:26.004+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:57:26.002+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:57:26.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:57:26.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.074 seconds
[2024-09-01T17:57:56.354+0000] {processor.py:161} INFO - Started process (PID=675) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:57:56.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:57:56.375+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:57:56.374+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:57:56.433+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:57:56.430+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:57:56.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:57:56.518+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.193 seconds
[2024-09-01T17:58:26.817+0000] {processor.py:161} INFO - Started process (PID=686) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:58:26.819+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:58:26.825+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:58:26.824+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:58:26.849+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:58:26.848+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:58:26.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:58:26.877+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.067 seconds
[2024-09-01T17:58:57.095+0000] {processor.py:161} INFO - Started process (PID=697) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:58:57.096+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:58:57.098+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:58:57.098+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:58:57.113+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:58:57.112+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:58:57.114+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:58:57.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.054 seconds
[2024-09-01T17:59:28.302+0000] {processor.py:161} INFO - Started process (PID=708) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:59:28.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:59:28.323+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:59:28.322+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:59:28.830+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:59:28.815+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:59:28.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:59:29.042+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.764 seconds
[2024-09-01T17:59:59.282+0000] {processor.py:161} INFO - Started process (PID=725) to work on /opt/airflow/dags/etl.py
[2024-09-01T17:59:59.283+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T17:59:59.286+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:59:59.285+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T17:59:59.311+0000] {logging_mixin.py:188} INFO - [2024-09-01T17:59:59.309+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T17:59:59.313+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T17:59:59.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.077 seconds
[2024-09-01T18:00:29.882+0000] {processor.py:161} INFO - Started process (PID=736) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:00:29.892+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:00:29.897+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:00:29.896+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:00:30.295+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:00:30.293+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:00:30.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:00:30.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.536 seconds
[2024-09-01T18:01:01.643+0000] {processor.py:161} INFO - Started process (PID=747) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:01:01.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:01:01.699+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:01:01.698+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:01:02.002+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:01:01.999+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:01:02.003+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:01:02.107+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.490 seconds
[2024-09-01T18:01:33.235+0000] {processor.py:161} INFO - Started process (PID=758) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:01:33.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:01:33.252+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:01:33.251+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:01:33.293+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:01:33.290+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:01:33.297+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:01:33.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.203 seconds
[2024-09-01T18:02:03.940+0000] {processor.py:161} INFO - Started process (PID=771) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:02:03.947+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:02:03.955+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:02:03.951+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:02:03.987+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:02:03.985+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:02:03.990+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:02:04.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.181 seconds
[2024-09-01T18:02:35.801+0000] {processor.py:161} INFO - Started process (PID=782) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:02:35.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:02:35.959+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:02:35.959+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:02:36.987+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:02:36.985+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:02:37.002+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:02:37.074+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 1.295 seconds
[2024-09-01T18:03:07.762+0000] {processor.py:161} INFO - Started process (PID=794) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:03:07.764+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:03:07.768+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:03:07.767+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:03:07.803+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:03:07.800+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:03:07.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:03:07.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.121 seconds
[2024-09-01T18:03:38.584+0000] {processor.py:161} INFO - Started process (PID=804) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:03:38.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:03:38.601+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:03:38.600+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:03:38.682+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:03:38.680+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:03:38.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:03:38.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.243 seconds
[2024-09-01T18:04:09.379+0000] {processor.py:161} INFO - Started process (PID=815) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:04:09.381+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:04:09.395+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:04:09.384+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:04:09.494+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:04:09.491+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:04:09.496+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:04:09.586+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.241 seconds
[2024-09-01T18:04:41.160+0000] {processor.py:161} INFO - Started process (PID=826) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:04:41.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:04:41.189+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:04:41.188+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:04:41.445+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:04:41.442+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:04:41.450+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:04:41.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.460 seconds
[2024-09-01T18:05:15.642+0000] {processor.py:161} INFO - Started process (PID=836) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:05:15.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:05:15.755+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:05:15.755+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:05:19.837+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:05:19.834+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:05:20.054+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:05:20.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 4.731 seconds
[2024-09-01T18:05:55.413+0000] {processor.py:161} INFO - Started process (PID=847) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:05:55.462+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:05:55.481+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:05:55.480+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:05:55.602+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:05:55.599+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:05:55.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:05:55.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.316 seconds
[2024-09-01T18:06:26.731+0000] {processor.py:161} INFO - Started process (PID=858) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:06:26.747+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:06:26.754+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:06:26.754+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:06:26.882+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:06:26.880+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:06:26.885+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:06:26.949+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.239 seconds
[2024-09-01T18:06:57.227+0000] {processor.py:161} INFO - Started process (PID=869) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:06:57.229+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:06:57.235+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:06:57.234+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:06:57.259+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:06:57.257+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:06:57.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:06:57.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.091 seconds
[2024-09-01T18:07:27.712+0000] {processor.py:161} INFO - Started process (PID=880) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:07:27.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:07:27.765+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:07:27.765+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:07:27.789+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:07:27.787+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:07:27.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:07:27.822+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.132 seconds
[2024-09-01T18:07:58.410+0000] {processor.py:161} INFO - Started process (PID=892) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:07:58.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:07:58.415+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:07:58.414+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:07:58.448+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:07:58.445+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:07:58.450+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:07:58.486+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.089 seconds
[2024-09-01T18:08:30.344+0000] {processor.py:161} INFO - Started process (PID=903) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:08:30.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:08:30.385+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:08:30.384+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:08:30.954+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:08:30.951+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:08:30.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:08:31.068+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.757 seconds
[2024-09-01T18:09:01.462+0000] {processor.py:161} INFO - Started process (PID=914) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:09:01.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:09:01.515+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:09:01.514+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:09:01.607+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:09:01.605+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:09:01.609+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:09:01.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.283 seconds
[2024-09-01T18:09:32.033+0000] {processor.py:161} INFO - Started process (PID=925) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:09:32.042+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:09:32.049+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:09:32.047+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:09:32.092+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:09:32.089+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:09:32.095+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:09:32.203+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.203 seconds
[2024-09-01T18:10:03.872+0000] {processor.py:161} INFO - Started process (PID=943) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:10:03.943+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:10:03.976+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:10:03.975+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:10:04.162+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:10:04.159+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:10:04.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:10:04.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.428 seconds
[2024-09-01T18:10:34.736+0000] {processor.py:161} INFO - Started process (PID=954) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:10:34.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:10:34.755+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:10:34.754+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:10:35.047+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:10:35.044+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:10:35.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:10:35.194+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.485 seconds
[2024-09-01T18:11:06.288+0000] {processor.py:161} INFO - Started process (PID=965) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:11:06.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:11:06.355+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:11:06.353+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:11:06.551+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:11:06.549+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:11:06.553+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:11:06.604+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.341 seconds
[2024-09-01T18:11:36.905+0000] {processor.py:161} INFO - Started process (PID=976) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:11:36.908+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:11:36.913+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:11:36.913+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:11:36.956+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:11:36.954+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:11:36.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:11:37.027+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.142 seconds
[2024-09-01T18:12:07.621+0000] {processor.py:161} INFO - Started process (PID=987) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:12:07.626+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:12:07.631+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:12:07.630+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:12:07.695+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:12:07.693+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:12:07.697+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:12:07.749+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.147 seconds
[2024-09-01T18:12:37.925+0000] {processor.py:161} INFO - Started process (PID=998) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:12:37.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:12:37.937+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:12:37.936+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:12:37.988+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:12:37.985+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:12:38.001+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:12:38.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.224 seconds
[2024-09-01T18:13:08.274+0000] {processor.py:161} INFO - Started process (PID=1009) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:13:08.275+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:13:08.278+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:13:08.278+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:13:08.299+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:13:08.296+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:13:08.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:13:08.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.109 seconds
[2024-09-01T18:13:38.581+0000] {processor.py:161} INFO - Started process (PID=1019) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:13:38.583+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:13:38.593+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:13:38.592+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:13:38.667+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:13:38.665+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:13:38.669+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:13:38.708+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.146 seconds
[2024-09-01T18:14:09.000+0000] {processor.py:161} INFO - Started process (PID=1030) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:14:09.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:14:09.007+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:14:09.006+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:14:09.026+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:14:09.024+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:14:09.028+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:14:09.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.089 seconds
[2024-09-01T18:14:39.221+0000] {processor.py:161} INFO - Started process (PID=1042) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:14:39.223+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:14:39.225+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:14:39.225+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:14:39.250+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:14:39.247+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:14:39.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:14:39.284+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.071 seconds
[2024-09-01T18:15:09.602+0000] {processor.py:161} INFO - Started process (PID=1053) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:15:09.604+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:15:09.607+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:15:09.606+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:15:09.631+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:15:09.629+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 19
    df = pd.read_csv(f'C:\Users\Lawalson\my_etl_project{csv_file}')
                                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-09-01T18:15:09.632+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:15:09.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 0.074 seconds
[2024-09-01T18:15:40.518+0000] {processor.py:161} INFO - Started process (PID=1064) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:15:40.521+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:15:40.525+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:15:40.525+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:15:43.213+0000] {processor.py:840} INFO - DAG(s) 'ingest_ecommerce_data' retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:15:43.955+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:15:43.954+0000] {override.py:1858} INFO - Created Permission View: can edit on DAG:ingest_ecommerce_data
[2024-09-01T18:15:43.987+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:15:43.986+0000] {override.py:1858} INFO - Created Permission View: can delete on DAG:ingest_ecommerce_data
[2024-09-01T18:15:44.027+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:15:44.026+0000] {override.py:1858} INFO - Created Permission View: can read on DAG:ingest_ecommerce_data
[2024-09-01T18:15:44.028+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:15:44.028+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-01T18:15:44.062+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:15:44.062+0000] {dag.py:3111} INFO - Creating ORM DAG for ingest_ecommerce_data
[2024-09-01T18:15:44.081+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:15:44.080+0000] {dag.py:3947} INFO - Setting next_dagrun for ingest_ecommerce_data to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2024-09-01T18:15:44.117+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 3.612 seconds
[2024-09-01T18:16:14.578+0000] {processor.py:161} INFO - Started process (PID=1076) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:16:14.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:16:14.582+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:16:14.582+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:16:16.596+0000] {processor.py:840} INFO - DAG(s) 'ingest_ecommerce_data' retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:16:16.759+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:16:16.758+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-01T18:16:16.877+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:16:16.876+0000] {dag.py:3947} INFO - Setting next_dagrun for ingest_ecommerce_data to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2024-09-01T18:16:17.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 2.659 seconds
[2024-09-01T18:16:48.030+0000] {processor.py:161} INFO - Started process (PID=1168) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:16:48.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:16:48.095+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:16:48.094+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:16:57.079+0000] {processor.py:840} INFO - DAG(s) 'ingest_ecommerce_data' retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:16:57.461+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:16:57.458+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-01T18:16:57.527+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:16:57.527+0000] {dag.py:3947} INFO - Setting next_dagrun for ingest_ecommerce_data to 2024-01-15 00:00:00+00:00, run_after=2024-01-16 00:00:00+00:00
[2024-09-01T18:16:58.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 11.055 seconds
[2024-09-01T18:17:29.891+0000] {processor.py:161} INFO - Started process (PID=1279) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:17:29.911+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:17:29.929+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:17:29.928+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:17:41.784+0000] {processor.py:840} INFO - DAG(s) 'ingest_ecommerce_data' retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:17:42.438+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:17:42.437+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-01T18:17:46.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 17.066 seconds
[2024-09-01T18:18:17.757+0000] {processor.py:161} INFO - Started process (PID=1387) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:18:17.778+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:18:17.826+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:18:17.824+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:18:29.275+0000] {processor.py:840} INFO - DAG(s) 'ingest_ecommerce_data' retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:18:30.476+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:18:30.475+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-01T18:18:34.800+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 17.175 seconds
[2024-09-01T18:19:05.886+0000] {processor.py:161} INFO - Started process (PID=1419) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:19:05.898+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:19:05.905+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:19:05.904+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:19:08.375+0000] {processor.py:840} INFO - DAG(s) 'ingest_ecommerce_data' retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:19:08.610+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:19:08.609+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-01T18:19:08.870+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 3.020 seconds
[2024-09-01T18:19:40.093+0000] {processor.py:161} INFO - Started process (PID=1432) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:19:40.110+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:19:40.115+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:19:40.114+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:19:42.247+0000] {processor.py:840} INFO - DAG(s) 'ingest_ecommerce_data' retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:19:42.426+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:19:42.415+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-01T18:19:42.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 2.596 seconds
[2024-09-01T18:20:12.910+0000] {processor.py:161} INFO - Started process (PID=1451) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:20:12.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:20:12.920+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:20:12.919+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:20:15.003+0000] {processor.py:840} INFO - DAG(s) 'ingest_ecommerce_data' retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:20:15.182+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:20:15.181+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-01T18:20:15.522+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 2.622 seconds
[2024-09-01T18:20:46.343+0000] {processor.py:161} INFO - Started process (PID=1464) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:20:46.344+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:20:46.347+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:20:46.346+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:20:47.019+0000] {processor.py:840} INFO - DAG(s) 'ingest_ecommerce_data' retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:20:47.065+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:20:47.064+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-01T18:20:47.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 1.048 seconds
[2024-09-01T18:21:18.123+0000] {processor.py:161} INFO - Started process (PID=1476) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:21:18.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:21:18.141+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:21:18.140+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:21:19.358+0000] {processor.py:840} INFO - DAG(s) 'ingest_ecommerce_data' retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:21:19.621+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:21:19.620+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-01T18:21:20.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 2.126 seconds
[2024-09-01T18:21:51.389+0000] {processor.py:161} INFO - Started process (PID=1523) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:21:51.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:21:51.504+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:21:51.503+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:21:57.927+0000] {processor.py:840} INFO - DAG(s) 'ingest_ecommerce_data' retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:22:01.874+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:22:01.873+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-01T18:22:03.217+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 12.056 seconds
[2024-09-01T18:22:35.263+0000] {processor.py:161} INFO - Started process (PID=1623) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:22:35.433+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:22:35.594+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:22:35.537+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:22:47.532+0000] {processor.py:840} INFO - DAG(s) 'ingest_ecommerce_data' retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:22:47.939+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:22:47.935+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-01T18:22:48.383+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:22:48.383+0000] {dag.py:3947} INFO - Setting next_dagrun for ingest_ecommerce_data to 2024-01-17 00:00:00+00:00, run_after=2024-01-18 00:00:00+00:00
[2024-09-01T18:22:48.844+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 13.664 seconds
[2024-09-01T18:23:20.050+0000] {processor.py:161} INFO - Started process (PID=1737) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:23:20.099+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:23:20.160+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:23:20.159+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:23:32.438+0000] {processor.py:840} INFO - DAG(s) 'ingest_ecommerce_data' retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:23:32.876+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:23:32.875+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-01T18:23:33.779+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:23:33.778+0000] {dag.py:3947} INFO - Setting next_dagrun for ingest_ecommerce_data to 2024-01-20 00:00:00+00:00, run_after=2024-01-21 00:00:00+00:00
[2024-09-01T18:23:34.550+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 14.713 seconds
[2024-09-01T18:24:10.172+0000] {processor.py:161} INFO - Started process (PID=1818) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:24:10.250+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:24:10.314+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:24:10.313+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:24:26.860+0000] {processor.py:840} INFO - DAG(s) 'ingest_ecommerce_data' retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:24:28.670+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:24:28.669+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-01T18:24:34.358+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:24:34.357+0000] {dag.py:3947} INFO - Setting next_dagrun for ingest_ecommerce_data to 2024-01-22 00:00:00+00:00, run_after=2024-01-23 00:00:00+00:00
[2024-09-01T18:24:35.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 25.459 seconds
[2024-09-01T18:25:06.156+0000] {processor.py:161} INFO - Started process (PID=1943) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:25:06.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:25:06.173+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:25:06.172+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:25:09.379+0000] {processor.py:840} INFO - DAG(s) 'ingest_ecommerce_data' retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:25:09.528+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:25:09.527+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-01T18:25:10.369+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:25:10.369+0000] {dag.py:3947} INFO - Setting next_dagrun for ingest_ecommerce_data to 2024-01-24 00:00:00+00:00, run_after=2024-01-25 00:00:00+00:00
[2024-09-01T18:25:10.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 4.686 seconds
[2024-09-01T18:26:04.066+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/etl.py
[2024-09-01T18:26:04.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2024-09-01T18:26:04.099+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:26:04.098+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2024-09-01T18:26:17.046+0000] {processor.py:840} INFO - DAG(s) 'ingest_ecommerce_data' retrieved from /opt/airflow/dags/etl.py
[2024-09-01T18:26:19.674+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:26:19.673+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-09-01T18:26:20.799+0000] {logging_mixin.py:188} INFO - [2024-09-01T18:26:20.798+0000] {dag.py:3947} INFO - Setting next_dagrun for ingest_ecommerce_data to 2024-01-29 00:00:00+00:00, run_after=2024-01-30 00:00:00+00:00
[2024-09-01T18:26:21.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl.py took 17.663 seconds
